### ISSUE TITLE
16 keypoint & 17 keypoints problem

### ISSUE THREAD

**Issue by liuyangme** [nies14/RS-Net#1]
Hello! Thank you for open sourcing such outstanding research work!
In my recent reading of your paper and code I have encountered a few things that confuse me. (1) In the code the human inputs and outputs are based on 16 keypoints, but in the paper, both the figure and the visualization of the experimental results show the results of 17 keypoints, and I can't understand why this difference has been generated. (2) In addition, in terms of comparison of results, is the other method based on the 16 keypoint results or the 17 keypoints, and would there be any fairness issues in comparing the 16 keypoints with the 17 keypoints results.
Thank you for taking the time to answer and help.

**Comment by nies14** [comment]
Hi @liuyang9609 ,
Thanks for your interest in our work. 

For CPN - We use 17 keypoints.
For Detectron - We use 17 keypoints
For GT & HRNet - We use 16 keypoints following prior works. And, we get the best results using HRNet for detected 2D keypoints. The visualization figure is done using CPN in order to compare with the baseline model. That can also be done using 16 keypoints. You can follow this work [MLP-Graph](https://github.com/nies14/Spatio-Temporal-MLP-Graph) , if you want to visualize with 16 keypoints.

**Comment by liuyangme** [comment]
Thank you for taking the time to answer my question.

And where do I find the code for the 17 keypoints?
Or what parts of the code need to be changed to modify the code program for the 17 keypoints, can you give some suggestions?

Looking forward to your reply.

**Comment by nies14** [comment]
You can follow [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) for 17 keypoints. FYI, they don't use HRNet.

For changing, from this line [h36m_dataset.py](https://github.com/nies14/RS-Net/blob/bd2641185f54929914559687b02f4afab4267f1a/data/common/h36m_dataset.py#L273), you just need to remove `x == 'Neck/Nose'`

and you also need to change `train_graph_time.py` file following [this](https://github.com/vanoracai/Exploiting-Spatial-temporal-Relationships-for-3D-Pose-Estimation-via-Graph-Convolutional-Networks/blob/master/train_graph_time.py). They also don't use HRNet.

**Comment by liuyangme** [comment]
Thanks for your time.
My confusion is solved and I will close this issue.
I may cite your paper in my future work.
